name: Tessera Docker Push

on:
  push:
    branches:
      - master

jobs:
  push-latest:
    name: Build and push latest Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_REPO }}
          tags: develop
          add_git_labels: true
