name: Tessera Docker Push

on:
  push:
    branches:
      - master
    tags:
      - tessera-*

jobs:
  push-latest:
    name: Push latest
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_REPO }}
          tags: latest
          add_git_labels: true
  push-tag:
    name: Push tag
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/tessera-')
    steps:
      - uses: actions/checkout@v2
      - name: Determine tag name
        id: tag
        run: |
          REF=${{ github.ref }}
          echo ::set-output name=name::$(echo $REF | sed 's/refs\/tags\/tessera-//g')
          echo ::set-output name=minor::$(echo $REF | sed -e 's/refs\/tags\/tessera-//g' -e 's/^\([[:digit:]]*\.[[:digit:]]*\).*/\1/')
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_REPO }}
          tags: ${{ steps.tag.outputs.name }}, ${{ steps.tag.outputs.minor }}
          add_git_labels: true
