name: Tessera Gradle Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  GRADLE_CACHE_KEY: ${{ github.run_id }}-gradle-${{ github.run_number }}-${{ github.run_number }}-${{ github.sha }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -x test -x dependencyCheckAnalyze
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ env.GRADLE_CACHE_KEY }}
        restore-keys: |
          ${{ env.GRADLE_CACHE_KEY }}
    - uses: actions/upload-artifact@v1
      if: success()
      with:
        name: tessera-jars
        path: /home/runner/work/tessera/tessera/tessera-dist/tessera-app/build/libs/

  checkdependencies:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ env.GRADLE_CACHE_KEY }}
        restore-keys: |
          ${{ env.GRADLE_CACHE_KEY }}
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: ./gradlew dependencyCheckAnalyze -x test

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ env.GRADLE_CACHE_KEY }}
        restore-keys: |
          ${{ env.GRADLE_CACHE_KEY }}
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: ./gradlew test -x dependencyCheckAnalyze  -x :tests:acceptance-test:test --info
  itest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ env.GRADLE_CACHE_KEY }}
        restore-keys: |
          ${{ env.GRADLE_CACHE_KEY }}
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - run: ./gradlew :tests:acceptance-test:test -PexcludeTests="RecoverIT,RestSuiteHttpH2RemoteEnclave"
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
       name: itest-junit-report
       path: /home/runner/work/tessera/tessera/tests/acceptance-test/build/reports/tests/

  remote_enclave_itest:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ env.GRADLE_CACHE_KEY }}
          restore-keys: |
            ${{ env.GRADLE_CACHE_KEY }}
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew :tests:acceptance-test:test --tests RestSuiteHttpH2RemoteEnclave
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: remote_enclave_itest-junit-report
          path: /home/runner/work/tessera/tessera/tests/acceptance-test/build/reports/tests/

#  recovery_itest:
#    runs-on: ubuntu-latest
#    needs: [build]
#    steps:
#    - uses: actions/checkout@v2
#
#    - uses: actions/cache@v1
#      with:
#        path: ~/.gradle/caches
#        key: ${{ env.GRADLE_CACHE_KEY }}
#        restore-keys: |
#          ${{ env.GRADLE_CACHE_KEY }}
#    - uses: actions/setup-java@v1
#      with:
#        java-version: 11
#      - run: ./gradlew :tests:acceptance-test:test --tests RecoverIT
#    - uses: actions/upload-artifact@v1
#      if: failure()
#      with:
#          name: recovery_itest-junit-report
#       path: /home/runner/work/tessera/tessera/tests/acceptance-test/build/reports/tests/

  atest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ env.GRADLE_CACHE_KEY }}
          restore-keys: |
            ${{ env.GRADLE_CACHE_KEY }}
      - run: |
          ./gradlew build -x test -x dependencyCheckAnalyze -x javadoc
      - uses: docker/build-push-action@v1
        with:
          repository: quorumengineering/tessera
          tags: latest
          push: false
          dockerfile: .github/workflows/DockerfileTest
          build_args: JAR_FILE=tessera-dist/tessera-app/build/libs/tessera-app-*-app.jar
      - run:
          docker run --rm --network host -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/acctests:/tmp/acctests quorumengineering/acctests:latest test -Pauto -Dtags="!async && (basic || basic-istanbul || networks/typical::istanbul)" -Dauto.outputDir=/tmp/acctests -Dnetwork.forceDestroy=true
