name: Tessera Release Build

on:
  repository_dispatch:
    types: [release]

env:
  SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
  SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
  GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
  GPG_EXECUTABLE: ${{ secrets.GPG_EXECUTABLE }}
  GPG_SECRET_KEYS: ${{ secrets.GPG_SECRET_KEYS }}

jobs:
  checkdependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: ./gradlew dependencyCheckAnalyze -x test
  release:
    needs: checkdependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Release
        id: release
        run: |
          git config user.name "quorumbot"
          now=`date +%Y%m%d%H%M%S`
          tagversion=`cat version.txt | cut -d'-' -f1`
          tagname="tessera-$tagversion"
          echo "$tagversion" > version.txt
          git add version.txt
          git commit -m "Change to release version $tagversion"
          git tag -a $tagname -m "Release tessera $tagversion"
          git push --tags

          echo "${GPG_SECRET_KEYS}" | base64 --decode | gpg --import --no-tty --batch --yes
          echo $GPG_OWNERTRUST | base64 --decode | gpg --import-ownertrust
          pubkey=`gpg --list-keys -a info@goquorum.com|head -2|tail -1|xargs`
          ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -PsonatypeUsername=$SONATYPE_USERNAME -PsonatypePassword=$SONATYPE_PASSWORD -Psigning.gnupg.keyName=$pubkey --info
          ./gradlew incrementProjectVersion --info
          git add version.txt
          git commit -m "Change version to next development version"

          minor_version=${tagversion%.*}
          echo ::set-output name=full-ver::$tagversion
          echo ::set-output name=minor-ver::$minor_version
          echo ::set-output name=branch-name::release-$now
      - name: Create PR to update development version
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ steps.release.outputs.branch-name }}
          title: Update development version
          body: Triggered by release https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Save tessera-app.jar
        uses: actions/upload-artifact@v2
        with:
          name: tessera-app
          path: tessera-dist/tessera-app/build/libs/tessera-app-*-app.jar
      - name: Push Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_REPO }}
          tags: ${{ steps.release.outputs.full-ver }}, ${{ steps.release.outputs.minor-ver }}, latest
          add_git_labels: true
          dockerfile: .github/workflows/noBuild.Dockerfile
          path: tessera-dist/tessera-app/build/libs
          build_args: JAR_FILE=tessera-app-${{ steps.release.outputs.full-ver }}-app.jar
