name: Update OpenAPI Document
on:
  push:
    branches:
      - master
    paths:
      - 'tessera-jaxrs/**'
env:
  TESSERA_DIR: tessera
  DOC_DIR: gh-pages
  DOC_REF: refs/heads/gh-pages
  DOC_OPENAPI_PATH: tessera_rest_openapi3_spec.latest.yaml
  TESSERA_OPENAPI_PATH: tessera-jaxrs/generate-openapi/build/generated-resources/openapi/openapi.yaml
jobs:
  run:
    name: Check for updates and raise PR
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          ref: ${{ env.DOC_REF }}
          path: ${{ env.DOC_DIR }}
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          path: ${{ env.TESSERA_DIR }}
      - name: Grant execute permission for gradlew
        working-directory: ${{ env.TESSERA_DIR }}
        run: chmod +x gradlew
      - name: Generate OpenAPI document
        working-directory: ${{ env.TESSERA_DIR }}
        run: ./gradlew -Dorg.gradle.jvmargs=-Xmx4096m generateOpenApiDoc
      - name: Copy OpenAPI document to ${{ env.DOC_DIR }}
        run: |
          cp ${{ env.TESSERA_DIR }}/${{ env.TESSERA_OPENAPI_PATH }} ${{ env.DOC_DIR }}/${{ env.DOC_OPENAPI_PATH }}
      - name: Raise PR if any changes
        id: pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.QUORUMBOT_PAT }}
          path: ${{ env.DOC_DIR }}
          commit-message: Automated openapi doc update
          branch: automated-openapi-update
          delete-branch: true
          title: Automated openapi doc update
          body: Automated update of openapi documentation triggered by ref=${{ github.ref }} sha=${{ github.sha }}
      - name: Summary
        run: |
          echo "Triggered by ${{ github.ref }} ${{ github.sha }}"
          echo "Created PR ${{ steps.pr.outputs.pull-request-url }}"


